### ISSUE TITLE
Username/password valid but not working on CLI

### ISSUE THREAD

**Issue by bruxelles86** [cloudfoundry-incubator/credhub-cli#43]
What version of the credhub server you are using?

BOSH release 1.9.1

What version of the credhub cli you are using?

1.7.5

If you were attempting to accomplish a task, what was it you were attempting to do?

We're trying to login to Credhub on the CLI with our username and password.

What did you expect to happen?

We expected to be able to login successfully.

What was the actual behavior?

```
$ credhub login
username: credhub-cli
password: ********************
The provided credentials are incorrect. Please validate your input and retry your request.
```

Despite this, the *exact same* credentials allow us to login to `https://<concourse-web-node-IP>:8443/login`

Here's the relevant chunk of the properties for the UAA job in our Concourse BOSH manifest:

```
        scim:
          users:
          - name: admin
            password: ((uaa-users-admin))
            groups:
            - scim.write
            - scim.read
            - bosh.admin
            - credhub.read
            - credhub.write
          - name: credhub-cli
            password: ((credhub_cli_password))
            groups:
            - credhub.read
            - credhub.write
        clients:
          credhub_cli:
            override: true
            authorized-grant-types: password,refresh_token,client_credentials
            scope: credhub.read,credhub.write
            authorities: uaa.resource,credhub.read,credhub.write
            access-token-validity: 30
            refresh-token-validity: 3600
            secret: ((credhub_cli_password))
          atc_to_credhub:
            override: true
            authorized-grant-types: client_credentials
            scope: ""
            authorities: credhub.read,credhub.write
            access-token-validity: 3600
            secret: ((uaa_clients_atc_to_credhub))
```

Please confirm where necessary:
* [ X ] I have included a log output
* [ X ] My log includes an error message
* [ X ] I have included steps for reproduction

Thanks!
