### ISSUE TITLE
Failed import should return non-zero exit code

### ISSUE THREAD

**Issue by jhamon** [cloudfoundry-incubator/credhub-cli#52]
**What version of the credhub server you are using?
What version of the credhub cli you are using?**

```
credhub --version
CLI Version: 1.7.7
Server Version: 0.0.0
```

**If you were attempting to accomplish a task, what was it you were attempting to do?**

I am trying to bulk import credentials using the `import` command. E.g. `credhub import -f notification-creds.yml`

My notification-creds.yml file looks something like this

```
---
credentials:
- name: /bosh-oms/notifications/domain
  type: domain
  value: my.domain.com
- name: /bosh-oms/notifications/encryption_key
  type: string
  value: moons_of_endor

```

**What did you expect to happen?**

I expected a non-zero exit code when credential import is unsuccessful.

**What was the actual behavior?**

I see output telling me it was unsuccessful

> Credential '/bosh-oms/notifications/domain' at index 0 could not be set: The request does not include a valid type. Valid values include 'value', 'json', 'password', 'user', 'certificate', 'ssh' and 'rsa'.
Credential '/bosh-oms/notifications/encryption_key' at index 1 could not be set: The request does not include a valid type. Valid values include 'value', 'json', 'password', 'user', 'certificate', 'ssh' and 'rsa'.

but I can `echo $?` to see the exit code was 0. This makes it difficult for my concourse pipeline to fail at the appropriate time.
