### ISSUE TITLE
add a key-value pair format for `credhub export`

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-incubator/credhub-cli#56]
> What version of the credhub server you are using?

`master`

> What version of the credhub cli you are using?

`2.0.0`

> If you were attempting to accomplish a task, what was it you were attempting to do?

After a discussing with @athornton2012 and @TisVictress, we'd like to propose an additional format for `credhub export`.

The current export has a structure with made for easy importing into another Credhub.

We'd like to have a format that make it easier to consume the variables for YAML interpolation. This interpolation would not happen via a bosh director / concourse `atc`. This is for another CLI.

For example, the current output of a `credhub export`:

```yaml
type: user
name: /example-user
value:
  username: FQnwWoxgSrDuqDLmeLpU
  password: 6mRPZB3bAfb8lRpacnXsHfDhlPqFcjH2h9YDvLpL
  password_hash: $6$h3b3JsG5$MnrPIrF6T3zAWk9uaun64vWY.vaBQ5nTRFZjjVqKuDWccxWXn8n6vstQykXEReamb4GYh2q1HC7vFy11wflXd0
```

The output format that we'd like to add, perhaps as `credhub export --format simple`.

```yaml
example-user_username: FQnwWoxgSrDuqDLmeLpU
example-user_password: 6mRPZB3bAfb8lRpacnXsHfDhlPqFcjH2h9YDvLpL
```

_NOTE:_ The pattern is useful because it prevents object collision when using YAML interpolation.

The above format allows YAML interpolation in a config file like:

```yaml
some-config: value
username: ((/example-user_username))
password: ((/example-user_password))
```

We'd like to add this capability to `credhub` CLI because we don't want our CLI to have a direct dependency on a credhub server.

> What did you expect to happen?

N/A

> What was the actual behavior?

N/A

**Comment by jtarchie** [comment]
To follow up with the _vision_ of this story.

This is the proposed implementation and "sort-of" story in our backlog.

I set some credentials in credhub

`creds.yml` an example creds file to be imported

```yaml
credentials:
- name: /p-automator/some-path/password
  type: password
  value: test-password-value
- name: /p-automator/some-path/value
  type: value
  value: test-value
- name: /p-automator/some-path/certificate
  type: certificate
  value:
    ca: ca-certificate
    certificate: certificate
    private_key: private-key
- name: /p-automator/some-path/rsa
  type: rsa
  value:
    public_key: public-key
    private_key: private-key
- name: /p-automator/some-path/ssh
  type: ssh
  value:
    public_key: ssh-public-key
    private_key: private-key
- name: /p-automator/some-path/user
  type: user
  value:
    username: covfefe
    password: test-user-password
- name: /p-automator/some-path/json
  type: json
  value:
    arbitrary_object:
      nested_array:
      - array_val1
      - array_object_subvalue: covfefe
    1: key is not a string
    3.14: pi
    true: key is a bool
```

```bash
$ credhub login
$ credhub import -f creds.yml
```

in a concourse pipeline far away

```yaml
- task: get credentials
  file: platform-automation-tasks/tasks/credhub-lookup.yml
  params:
  	# these are stored in concourse's credhub -- path /concourse/team-name/pipeline-name
  	CREDHUB_SERVER: ((credhub-url))
  	CREDHUB_USERNAME: ((credhub-username))
  	CREDHUB_PASSWORD: ((credhub-password))
  	CREDHUB_PATH: /p-automator/some-path # this the prefix path of the cred set above
```

This task produces an `output` (`vars.yml`) that would look like:

```yaml
password: test-password-value
value: test-value
certificate_ca: ca-certificate
certificate_certificate: certificate
certificate_private_key: private-key
rsa_public_key: public-key
rsa_private_key: private-key
ssh_public_key: ssh-public-key
ssh_private_key: private-key
user_username: covfefe
user_password: test-user-password
json: |
	{
		"arbitrary_object": {
			"nested_array": [
				"array_val1",
				{
					"array_object_subvalue": "covfefe"
				}
			]
		},
		"1": "key is not a string",
		"3.14": "pi",
		"true": "key is a bool"
	}
```
